### ISSUE TITLE
Support custom headers

### ISSUE THREAD

**Issue by ivarconr** [ivarconr/unleash-client-dart#14]
As far as I can understand there is no way to provide customer header fields without providing your own implementation of Unleash settings. It would be good if this SDK could support custom headers as unleash Enterprise v3 requires the Authorization set with an API key. In addition we will release Unleash V4 where also the open source version will require the API token set as the Authorization header.

**Comment by ueman** [comment]
It's actually possible by using your own [http.Client](https://pub.dev/documentation/http/latest/http/Client-class.html). Though it's definitely not a great solution if it's mandatory in the next version.

Thanks for the heads up.

Do you mind linking the relevant docs?

**Comment by ivarconr** [comment]
> It's actually possible by using your own [http.Client](https://pub.dev/documentation/http/latest/http/Client-class.html). Though it's definitely not a great solution if it's mandatory in the next version.

Ah, I missed that.

> Do you mind linking the relevant docs?

- https://docs.getunleash.io/docs/user_guide/api-token
- https://docs.getunleash.io/docs/deploy/migration_guide#upgrading-from-v3x-to-v4x

**v4 is already available in our free demo instances:**
- OSS: https://unleash.herokuapp.com/
- Enterprise: https://app.unleash-hosted.com/demo

**Comment by ueman** [comment]
Thanks!

**Comment by Philip-Nunoo** [comment]
https://github.com/ueman/unleash/pull/16 I believe this PR should fix the issue. Using the repo directly now.

**Comment by ueman** [comment]
Yep, that's right. I want to add some more test and finish up metrics reporting before I do a release.

@Philip-Nunoo please let me know if you run into any issues.

**Comment by momrak** [comment]
Hi, @ueman . What is the status of this feature/next release? And also the project in general, is there any planned work going forward? :)

**Comment by ueman** [comment]
I'm not really maintaining this anymore as I don't use it anymore. I've already talked to @ivarconr about donating this library to @unleash, but I've no timeline or progress update on that.

**Comment by momrak** [comment]
I see. Thank you for the update

**Comment by ivarconr** [comment]
Ownership transfer in motion. 

On these notes, we would love to create a Flutter [Unleash Proxy](https://docs.getunleash.io/sdks/unleash-proxy) SDK instead of this service SDK, as flutter usually runs in the context of a user device.

**Comment by momrak** [comment]
That's great! 

Agreed, that would probably be best suited for the most use cases in this ecosystem.

Is there an issue or something I can follow for progress on either this service SDK, or the possible flutter proxy sdk?
